/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

/**
 *
 * @author abrah
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentro = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        panelObjetos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(15, 15, 18));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        panelCentro.setBackground(new java.awt.Color(15, 15, 18));
        panelCentro.setLayout(new java.awt.BorderLayout());

        titulo.setFont(new java.awt.Font("Haettenschweiler", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(225, 95, 40));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("DARK SOULS III");
        panelCentro.add(titulo, java.awt.BorderLayout.PAGE_START);

        panelObjetos.setOpaque(false);
        panelObjetos.setLayout(new java.awt.BorderLayout());
        panelCentro.add(panelObjetos, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelObjetos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
